//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic6_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artist()
        {
            this.vistavki = new HashSet<vistavki>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string place_bith { get; set; }
        public System.DateTime bday { get; set; }
        public string disc_artist { get; set; }
        public string education { get; set; }
        public Nullable<int> id_work { get; set; }
    
        public virtual work work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vistavki> vistavki { get; set; }
    }
}
