//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic6_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class hall
    {
        public int id { get; set; }
        public string name { get; set; }
        public int sqare { get; set; }
        public int phone { get; set; }
        public Nullable<int> id_vistavki { get; set; }
        public Nullable<int> id_vladelec { get; set; }
    
        public virtual vistavki vistavki { get; set; }
        public virtual vladelec vladelec { get; set; }
    }
}
