//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic6_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class vladelec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vladelec()
        {
            this.hall = new HashSet<hall>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int pgone { get; set; }
        public Nullable<int> id_cityorg { get; set; }
    
        public virtual cityorg cityorg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hall> hall { get; set; }
    }
}
