//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic6_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work()
        {
            this.artist = new HashSet<artist>();
        }
    
        public int id { get; set; }
        public string kind_material { get; set; }
        public System.DateTime date_create { get; set; }
        public Nullable<int> id_razmer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artist> artist { get; set; }
        public virtual razmer razmer { get; set; }
    }
}
